check_android_task:
  name: Run Android instrumented tests
  env:
    SCREENSHOTS_ROOT_DIR: /data/data/com.kaspersky.kaspressample/files/screenshots
    TUTORIAL_SCREENSHOTS_ROOT_DIR: /data/data/com.kaspersky.kaspresso.tutorial/files/screenshots
    ALLURE_SAMPLE_SCREENSHOTS_ROOT_DIR: /data/data/com.kaspersky.kaspresso.alluresupport.sample/files/screenshots
    ALLURE_SAMPLE_FAIL_SCREENSHOTS_ROOT_DIR: /data/user/0/com.kaspersky.kaspresso.alluresupport.sample/files/screenshots
  only_if: $CIRRUS_PR != '' && $CIRRUS_BASE_BRANCH == 'master'

  container:
    image: cirrusci/android-sdk:30
    kvm: true
    cpu: 8
    memory: 24G
  tmp_script:
    echo `whoami`
  install_de_script: |
    addgroup --system xusers && adduser \
    			--home /home/xclient \
    			--disabled-password \
    			--shell /bin/bash \
    			--gecos "user for running an xclient application" \
    			--ingroup xusers \
    			--quiet \
    			cirrusci
    apt-get update && apt-get install -y --no-install-recommends \
    				xvfb \
    				rxvt \
    				xauth \
    				x11vnc \
    				x11-utils \
    				x11-xserver-utils
    mkdir -p /Xauthority && chown -R xclient:xusers /Xauthority
    export DISPLAY=:0.0
    mcookie | sed -e 's/^/add :0 MIT-MAGIC-COOKIE-1 /' | xauth -q
    xauth nlist :0 | sed -e 's/^..../ffff/' | xauth -f /Xauthority/xserver.xauth nmerge -
    Xvfb :0 -auth ~/.Xauthority -screen 0 $XFB_SCREEN >>~/xvfb.log 2>&1 &
    sleep 2
    x11vnc -forever -passwd $VNC_PASSWORD -display :0 &
    export DISPLAY=localhost:0
    xauth merge /Xauthority/xserver.xauth
  accept_licenses_script:
    echo yes | sdkmanager --licenses
  install_emulator_script:
    sdkmanager --install "system-images;android-30;google_apis;x86"
  create_avd_script:
    echo no | avdmanager create avd --force
    -n test
    -k "system-images;android-30;google_apis;x86"
  start_avd_background_script:
    $ANDROID_HOME/emulator/emulator
    -avd test
    -no-audio
    -no-boot-anim
    -gpu swiftshader_indirect
    -no-snapshot
  assemble_instrumented_tests_script:
    ./gradlew assembleDebugAndroidTest
  wait_for_avd_script:
    adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 3; done; input keyevent 82'
  configure_avd_script: |
    adb shell settings put global window_animation_scale 0.0
    adb shell settings put global transition_animation_scale 0.0
    adb shell settings put global animator_duration_scale 0.0
    adb shell settings put secure spell_checker_enabled 0
    adb shell settings put secure show_ime_with_hard_keyboard 1
  start_adb_server_background_script:
    java -jar artifacts/adbserver-desktop.jar || true
  run_tests_script: ./gradlew connectedDebugAndroidTest || mkdir sample_screenshots && adb root && for i in {1..5}; do adb pull $SCREENSHOTS_ROOT_DIR sample_screenshots; \
    mkdir tutorial_screenshots && adb pull $SCREENSHOTS_ROOT_DIR tutorial_screenshots; \
    mkdir allure_screenshots && adb pull $ALLURE_SAMPLE_FAIL_SCREENSHOTS_ROOT_DIR allure_screenshots; \
    adb pull $ALLURE_SAMPLE_SCREENSHOTS_ROOT_DIR allure_screenshots && break || sleep 5; done && return 1
  on_failure :
    sample_report_artifacts:
      path: "app/build/reports/androidTests/connected/**/*"
    tutorial_report_artifacts:
      path: "tutorial/build/reports/androidTests/connected/**/*"
    allure_report_artifacts:
      path: "kaspresso-allure-support-sample/build/reports/androidTests/connected/**/*"
    sample_screenshots_artifacts:
      path: "sample_screenshots/**/*"
    tutorial_screenshots_artifacts:
      path: "tutorial_screenshots/**/*"
    allure_screenshots_artifacts:
      path: "allure_screenshots/**/*"
