[versions]
kotlin = "1.4.32"
detekt = "1.18.1"
espresso = "3.4.0"
allure = "2.2.7"

[libraries]
# plugins
kotlinPlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
androidPlugin = "com.android.tools.build:gradle:4.1.0"

# libraries
kotlinCli = "org.jetbrains.kotlinx:kotlinx-cli:0.3"
detektCli = { module = "io.gitlab.arturbosch.detekt:detekt-cli", version.ref = "detekt" }
detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

kotlinStdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
espressoWeb = { module = "androidx.test.espresso:espresso-web", version.ref = "espresso" }
testCore = "androidx.test:core:1.4.0"
uiAutomator = "androidx.test.uiautomator:uiautomator:2.2.0"
fragmentTesting = "androidx.fragment:fragment-testing:1.3.6"
# upgrading to 4.6.1 is blocked by https://github.com/robolectric/robolectric/issues/6593
robolectric = "org.robolectric:robolectric:4.5.1"

androidXCore = "androidx.core:core:1.7.0"

androidXRules = "androidx.test:rules:1.4.0"
androidXTest = "androidx.test.ext:junit:1.1.3"
androidXTestKtx = "androidx.test.ext:junit-ktx:1.1.3"
composeUiTest = "androidx.compose.ui:ui-test:1.0.3"

appcompat = "androidx.appcompat:appcompat:1.3.0"
material = "com.google.android.material:material:1.2.0"
constraint = "androidx.constraintlayout:constraintlayout:2.0.0"

kakao = "io.github.kakaocup:kakao:3.0.5"
kakaoCompose = "io.github.kakaocup:compose:0.0.2"
gson = "com.google.code.gson:gson:2.8.6"

junit = "junit:junit:4.13"
junitJupiter = "org.junit.jupiter:junit-jupiter:5.6.2"
truth = "com.google.truth:truth:1.0"
runner = "androidx.test:runner:1.3.0"
orchestrator = "androidx.test:orchestrator:1.4.0"

okhttp = "com.squareup.okhttp3:okhttp:4.9.1"
kotson = "com.github.salomonbrys.kotson:kotson:2.5.0"

allureKotlinModel = { module = "io.qameta.allure:allure-kotlin-model", version.ref = "allure" }
allureKotlinCommons = { module = "io.qameta.allure:allure-kotlin-commons", version.ref = "allure" }
allureKotlinJunit4 = { module = "io.qameta.allure:allure-kotlin-junit4", version.ref = "allure" }
allureKotlinAndroid = { module = "io.qameta.allure:allure-kotlin-android", version.ref = "allure" }

[bundles]
espresso = ["espressoCore", "espressoWeb"]
allure = ["allureKotlinModel", "allureKotlinCommons", "allureKotlinJunit4", "allureKotlinAndroid"]
