# This workflow runs all the checks on pull requests

name: Pull Request Checks

on: pull_request

jobs:
  marathon_33:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Assemble android tests
        run: ./gradlew -PCI=true assembleDebugAndroidTest assembleDebug
      - name: Print
        run: find -name "*.apk"
      - name: run tests on android 33
        uses: MarathonLabs/action-test@0.3.3
        with:
          apiKey: ${{ secrets.marathon_github_token }}
          application: samples/kaspresso-sample/build/outputs/apk/debug/kaspresso-sample-debug.apk
          testApplication: samples/kaspresso-sample/build/outputs/apk/androidTest/debug/kaspresso-sample-debug-androidTest.apk
          platform: Android
          githubToken: ${{ secrets.GITHUB_TOKEN }}
