# This workflow runs all the checks on pull requests

name: PullRequest Checks

on: pull_request

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run static analysis
        run: ./gradlew detekt
      - name: Run unit tests
        run: ./gradlew test
      - name: Build project
        run: ./gradlew assemble
